server:
  port: 8080
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      storage-type: redis
      timeout: 1440m  # 1 day
      cookie:
        domain: localhost
        max-age: 1440m # 1 day

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  config:
    import:
      - classpath:oauth.yml
      - classpath:auth.yml
      - classpath:schedule.yml
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        check_nullability: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    show_sql: true
  batch:
    jdbc:
      initialize-schema: always
  data:
    redis:
      host: ${HELLO_REDIS_HOST}
      port: 6379
  cloud:
    aws:
      region:
        static: ap-northeast-2 # javadoc 설명에는 한국 리전을 지원 안한다고 쓰여있긴 함
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      sns:
        region: ap-northeast-1
      s3:
        region: ap-northeast-2
        bucket-name:  ${AWS_BUCKET_NAME}

logging:
  level:
    root: info
    org:
      hibernate.orm.jdbc.bind: trace # for parameter binding
    kr.hellogsm.back_v2_demo: trace
