name: Spring Boot & Gradle CI/CD 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Set up JDK 17 job has success
        if: ${{ success() }}
        run: echo "jdk 17 job succeeded"
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name : Setup Gradls's permission
        run : chmod +x gradlew 
      
      - name: Create application.yml
        run: |
          echo ${{ secrets.APPLICATION_OAUTH }} > ./hello-gsm-back-v2/src/main/resources/application-oauth.yml
          echo ${{ secrets.APPLICATION_SCHEDULE }} > ./hello-gsm-back-v2/src/main/resources/application-schedule.yml
          echo ${{ secrets.APPLICATION }} > ./hello-gsm-back-v2/src/main/resources/application.yml
        shell: bash
        
      - name: Build with Gradle
        run : ./gradlew clean build --exclude-task test
